# coding=utf-8

plugin_identifier = "e3s1p_bytt_thumbnails"
plugin_package = "octoprint_e3s1p_bytt_thumbnails"
plugin_name = "E3S1P ByTT Thumbnails"
plugin_version = "3.0.0"
plugin_description = """Originally based on the thumbnail extraction plugin by jneilliii and later enhancements by Thomas Toka, this plugin has been refactored and extended to support modern OctoPrint workflows.

It introduces an event-driven architecture that processes thumbnails at file upload time, enabling reliable operation with multiple uploaded files, out-of-order printing, and direct print workflows from slicers.

Supports thumbnails generated by PrusaSlicer, OrcaSlicer, Cura, CrealitySlicer, and SuperSlicer."""
plugin_author = "messedUpRyan"
plugin_author_email = "ryanterry_slc@outlook.com"
plugin_url = "https://github.com/messedUpRyan/OctoPrint-E3S1P_ByTT_thumbnails"
plugin_license = "AGPLv3"

# Any additional requirements besides OctoPrint should be listed here
plugin_requires = ["Pillow>=9.5.0", "standard-imghdr; python_version >= '3.11'"]
plugin_additional_data = []
plugin_additional_packages = []
plugin_ignored_packages = []
additional_setup_parameters = {"python_requires": ">=3.7,<4"}
########################################################################################################################

from setuptools import setup

try:
    import octoprint_setuptools
except:
    print(
        "Could not import OctoPrint's setuptools, are you sure you are running that under "
        "the same python installation that OctoPrint is installed under?"
    )
    import sys

    sys.exit(-1)

setup_parameters = octoprint_setuptools.create_plugin_setup_parameters(
    identifier=plugin_identifier,
    package=plugin_package,
    name=plugin_name,
    version=plugin_version,
    description=plugin_description,
    author=plugin_author,
    mail=plugin_author_email,
    url=plugin_url,
    license=plugin_license,
    requires=plugin_requires,
    additional_packages=plugin_additional_packages,
    ignored_packages=plugin_ignored_packages,
    additional_data=plugin_additional_data,
)


if len(additional_setup_parameters):
    from octoprint.util import dict_merge

    setup_parameters = dict_merge(setup_parameters, additional_setup_parameters)

setup(**setup_parameters)
